##################################
#Furniture
##################################

##Kitchen

cabinet:
  model: cabinet
  model_type: urdf.xacro
  position: [0,1.35,0]
  orientation: [0, 0, 0]

cabinet_diamondback:
  model: cabinet_diamondback
  model_type: urdf
  position: [-0.6, 1.47, 0.00]
  orientation: [0, 0, -1.570796327]

couch:
  model: couch
  model_type: urdf.xacro
  position: [3.6,0.6,0]
  orientation: [0, 0,-1.57079]

cabinet_ikea_galant:
  model: cabinet_ikea_galant
  model_type: urdf
  position: [1.30, 1.38, 0.00]
  orientation: [0, 0, 0]

chair_ikea_borje:
  model: chair_ikea_borje
  model_type: urdf
  position: [1.5, -0.8, 0.00]
  orientation: [0, 0, 0]

chair_ikea_borje2:
  model: chair_ikea_borje
  model_type: urdf
  position: [1.5, -2, 0.00]
  orientation: [0, 0, 3.141592654]

table_ikea_bjursta:
  model: table_ikea_bjursta
  model_type: urdf.xacro
  position: [1.5,-1.4, 0]
  orientation: [0, 0, 1.570796]

bookcase:
  model: bookcase
  model_type: urdf.xacro
  position: [3.95, -1.8, 0]
  orientation: [0, 0, 0]
